kinova_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 100

kinova_velocity_controller:
  type: "velocity_controller/JointVelocityController"
  publish_rate: 100