kinova_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 1000

kinova_velocity_controller:
  type: "velocity_controllers/JointGroupVelocityController"
  publish_rate: 1000
  joints:
    - joint_0
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
